version: "3.7"
services:
    nodeMySQL:
        image: mysql/mysql-server
        hostname: nodeMySQL
        ports:
            - "3307:3306"
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} 
        volumes:
            - "./dump:/docker-entrypoint-initdb.d"
            - persistent:/var/lib/mysql


    nodePMA:
        image: phpmyadmin/phpmyadmin
        links: 
            - nodeMySQL:db
        ports:
            - 8081:80
        environment:
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} 
    
volumes:
    persistent: 